/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.pro;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Weerasinghe
 */
public class reports extends javax.swing.JPanel {

    /**
     * Creates new form reports
     */
    Connection con ;
    public reports() {
        initComponents();
        con = db.mycon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        para_inid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        para_inid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        para_inid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                para_inidActionPerformed(evt);
            }
        });
        para_inid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                para_inidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                para_inidKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Invoke NO :");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("View All Sales");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(para_inid, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(para_inid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(408, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void para_inidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_para_inidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_para_inidActionPerformed

    private void para_inidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_para_inidKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_para_inidKeyPressed

    private void para_inidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_para_inidKeyReleased
       
    }//GEN-LAST:event_para_inidKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // View all sales report
        
  try {
            // Use the class loader to load the JRXML file from the classpath
            InputStream inputStream = getClass().getResourceAsStream("/reports/inreport.jrxml");

            // Check if the input stream is not null
            if (inputStream != null) {
                try {
                    JasperDesign jasdi = JRXmlLoader.load(inputStream);
                    String sql = "SELECT sales.`saleid` AS sales_saleid, sales.`INID` AS sales_INID, sales.`Cid` AS sales_Cid, sales.`Customer_Name` AS sales_Customer_Name, sales.`Total_Qty` AS sales_Total_Qty, sales.`Total_Bill` AS sales_Total_Bill, sales.`Status` AS sales_Status, sales.`Balance` AS sales_Balance FROM `sales` sales";
                    JRDesignQuery newQuery = new JRDesignQuery();
                    newQuery.setText(sql);
                    jasdi.setQuery(newQuery);
                    JasperPrint jp = JasperFillManager.fillReport(
                            JasperCompileManager.compileReport(jasdi),
                            null, con);

                    // Create JasperViewer
                    JasperViewer jasperViewer = new JasperViewer(jp, false);

                    // Set default close operation
                    jasperViewer.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

                    // Add WindowListener to handle window closing event
                    jasperViewer.addWindowListener(new WindowAdapter() {
                        @Override
                        public void windowClosing(WindowEvent e) {
                            // Handle closing event here if needed
                            // You can choose to dispose the viewer or take other actions
                            // For example, you might want to perform some cleanup
                        }
                    });

                    // Make the JasperViewer visible
                    jasperViewer.setVisible(true);

                } catch (JRException e) {
                    JOptionPane.showMessageDialog(para_inid, e);
                } finally {
                    try {
                        // Close the input stream in a finally block to ensure it's closed
                        inputStream.close();
                    } catch (IOException e) {
                        e.printStackTrace(); // Handle the exception appropriately
                    }
                }
            } else {
                System.err.println("JRXML file not found in the classpath");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(para_inid, e);
        }
  

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
try {
            // Create a parameter map
            Map<String, Object> parameters = new HashMap<>();

            // Put the parameter value into the map
            parameters.put("invoice_para", para_inid.getText());

            // Load the JRXML file using the class loader
            InputStream inputStream = getClass().getResourceAsStream("/reports/searchreport1.jrxml");

            // Check if the input stream is not null
            if (inputStream != null) {
                try {
                    JasperDesign jasdi = JRXmlLoader.load(inputStream);

                    // Set the SQL query for the report
                    String sql = "SELECT cart.`cartid` AS cart_cartid, cart.`INID` AS cart_INID, cart.`Product_Name` AS cart_Product_Name, cart.`Bar_code` AS cart_Bar_code, cart.`qty` AS cart_qty, cart.`Unit_Price` AS cart_Unit_Price, cart.`Total_Price` AS cart_Total_Price FROM `cart` cart WHERE INID = $P{invoice_para}";
                    JRDesignQuery newQuery = new JRDesignQuery();
                    newQuery.setText(sql);
                    jasdi.setQuery(newQuery);

                    // Compile the JasperReport
                    JasperReport js = JasperCompileManager.compileReport(jasdi);

                    // Fill the report with data using the parameter map
                    JasperPrint jp = JasperFillManager.fillReport(js, parameters, con);

                    // Create JasperViewer
                    JasperViewer jasperViewer = new JasperViewer(jp, false);

                    // Set default close operation
                    jasperViewer.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

                    // Add WindowListener to handle window closing event
                    jasperViewer.addWindowListener(new WindowAdapter() {
                        @Override
                        public void windowClosing(WindowEvent e) {
                            // Handle closing event here if needed
                            // You can choose to dispose the viewer or take other actions
                            // For example, you might want to perform some cleanup

                            // For now, let's just print a message to the console
                            System.out.println("JasperViewer is closing");
                        }
                    });

                    // Make the JasperViewer visible
                    jasperViewer.setVisible(true);
                } catch (JRException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(para_inid, e.getMessage());
                } finally {
                    try {
                        // Close the input stream in a finally block to ensure it's closed
                        inputStream.close();
                    } catch (IOException e) {
                        e.printStackTrace(); // Handle the exception appropriately
                    }
                }
            } else {
                System.err.println("JRXML file not found in the classpath");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(para_inid, e.getMessage());
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField para_inid;
    // End of variables declaration//GEN-END:variables
}
